services:
  ledger_postgres:
    image: postgres:16
    container_name: ledger_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - ledger_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  ledger_postgres_data: